const mongoose = require('mongoose')
const catalogFeedSchema = mongoose.Schema(
    {    
            itemNo: String,
            description1: String,
            description2: String,
            upc: String,
            manufacturerModelNo: String,
            msrp: Number,
            model: String,
            caliberGauge: String,
            manufacturer: String,
            type: String,
            action: String,
            barrelLength: String,
            capacity: String,
            finish: String,
            overallLength: String,
            receiver: String,
            safety: String,
            sights: String,
            stockFrameGrips: String,
            magazine: String,
            weight: String,
            imageName: String,
            chamber: String,
            drilledAndTapped: Boolean,
            rateOfTwist: String,
            itemType: String,
            additionalFeature1: String,
            additionalFeature2: String,
            additionalFeature3: String,
            shippingWeight: Number,
            boundBookManufacturer: String,
            boundBookModel: String,
            boundBookType: String,
            nfaThreadPattern: String,
            nfaAttachmentMethod: String,
            nfaBaffleType: String,
            silencerCanBeDisassembled: Boolean,
            silencerConstructionMaterial: String,
            nfaDbReduction: String,
            silencerOutsideDiameter: String,
            nfaForm3Caliber: String,
            opticMagnification: String,
            maintubeSize: String,
            adjustableObjective: Boolean,
            objectiveSize: String,
            opticAdjustments: String,
            illuminatedReticle: Boolean,
            reticle: String,
            exclusive: Boolean,
            quantity: Number,
            allocated: Boolean,
            onSale: Boolean,
            price: Number,
            currentPrice: Number,
            retailMap: Number,
            fflRequired: Boolean,
            sotRequired: Boolean,
            scopeCoverIncluded: Boolean,
            special: String,
            sightsType: String,
            case: String,
            choke: String,
            dbReduction: String,
            family: String,
            finishType: String,
            frame: String,
            gripType: String,
            handgunSlideMaterial: String,  
            countryOfOrigin: String,
            itemLength: String,
            itemWidth: String,
            itemHeight: String,
            packageLength: String,
            packageWidth: String,
            packageHeight: String,
            itemGroup: String
        }
    ,
    {
        timestamps: true
    }
)

const CatalogFeed = mongoose.model("CatalogFeed", catalogFeedSchema);
module.exports = CatalogFeed;